// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1naCB-sRkCVPZNcRh3uaLSE1o5QOXXOM',
    appId: '1:735361934571:web:15f112b6377c13a8d20aae',
    messagingSenderId: '735361934571',
    projectId: 'miniapp-sistemacadastro',
    authDomain: 'miniapp-sistemacadastro.firebaseapp.com',
    storageBucket: 'miniapp-sistemacadastro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQBSW8D2os0JXnlRj3O-o8VXkaolcZWI',
    appId: '1:735361934571:android:ea586ab19b8158a4d20aae',
    messagingSenderId: '735361934571',
    projectId: 'miniapp-sistemacadastro',
    storageBucket: 'miniapp-sistemacadastro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHDJ4AzGdIB2I7xhmhHN5Qydf5EzRX9s',
    appId: '1:735361934571:ios:d6b9175d8bb64389d20aae',
    messagingSenderId: '735361934571',
    projectId: 'miniapp-sistemacadastro',
    storageBucket: 'miniapp-sistemacadastro.appspot.com',
    iosBundleId: 'com.enercicio.enercicio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHDJ4AzGdIB2I7xhmhHN5Qydf5EzRX9s',
    appId: '1:735361934571:ios:d6b9175d8bb64389d20aae',
    messagingSenderId: '735361934571',
    projectId: 'miniapp-sistemacadastro',
    storageBucket: 'miniapp-sistemacadastro.appspot.com',
    iosBundleId: 'com.enercicio.enercicio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1naCB-sRkCVPZNcRh3uaLSE1o5QOXXOM',
    appId: '1:735361934571:web:32f0f34cba4d53a4d20aae',
    messagingSenderId: '735361934571',
    projectId: 'miniapp-sistemacadastro',
    authDomain: 'miniapp-sistemacadastro.firebaseapp.com',
    storageBucket: 'miniapp-sistemacadastro.appspot.com',
  );
}
